Feature task one
LumakanA/Notes pull request #2
Opened 2023-01-27 11:15 UTC by LumakanA

2023-01-29 08:42 UTC, Alexandr-Prokin requested changes

2023-01-29 08:42 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="385dp"
если удалить, что нибудь изменится? Там таких у тебя много

2023-01-29 08:42 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <EditText
размеры элемента делаем через margin

2023-01-29 08:42 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:lineHeight="15dp"
удалить

2023-01-29 08:42 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:minWidth="280dp"
удалить

2023-01-29 08:42 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:lineHeight="33dp"
удаляем

2023-01-29 13:55 UTC, Alexandr-Prokin requested changes
Если в одном месте написано, что нуждно минимальные размеры убрать, значит убрать надо везде

2023-01-29 13:55 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:minWidth="280dp"
А тут не будешь убирать минимальные размеры? Там много такого, везде надо убрать

2023-01-29 14:00 UTC, LumakanA commented on app/src/main/res/layout/activity_main.xml
> +        android:minWidth="280dp"
если их тут убрать, то текст съедет в центр. вопрос такой. можно все еще в первой ветке заменить EditText на com.google.android.material.textfield.TextInputEditText? или это уже делать во второй ветке?

2023-01-29 17:12 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:minWidth="280dp"
Через margin сделай размеры, можешь тут переделать либо во втором задании, без разницы

2023-01-31 18:15 UTC, Alexandr-Prokin requested changes
На макете не много по другому текст подсказки начинается
<img width="481" alt="Снимок экрана 2023-01-31 в 21 14 19" src="https://user-images.githubusercontent.com/35171601/215847861-1c5ce0b6-fca9-469f-9fb2-042b4a2cd1e0.png">

2023-02-01 07:42 UTC, Alexandr-Prokin requested changes
Запускал приложение?
<img width="817" alt="Снимок экрана 2023-02-01 в 10 40 33" src="https://user-images.githubusercontent.com/35171601/215981206-b4a00777-17d5-45d9-95ef-0c290a1d26c9.png">

2023-02-01 07:46 UTC, LumakanA commented
> Запускал приложение? <img alt="Снимок экрана 2023-02-01 в 10 40 33" width="817" src="https://user-images.githubusercontent.com/35171601/215981206-b4a00777-17d5-45d9-95ef-0c290a1d26c9.png">

ну для этого же скролл надо добавлять, а это уже во 2 ветке. разве не так?

2023-02-01 08:01 UTC, Alexandr-Prokin commented
Не так =) подвинь не много на верх, срок для другого будет делаться, когда много ошибок будет выходить и экран вынужден раздвигатсья

2023-02-01 10:25 UTC, merged