Feature task two
LumakanA/Notes pull request #3
Opened 2023-02-04 19:19 UTC by LumakanA

2023-02-05 05:59 UTC, Alexandr-Prokin requested changes
При пустом поле пароля, проходит валидацию

2023-02-05 05:59 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/notes/MainActivity.kt
> +            if (validateEmail(email) == null
Подумай над оптимизацией проверки, некоторые действия повторяются 2 раза

2023-02-05 11:47 UTC, Alexandr-Prokin requested changes

2023-02-05 11:47 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/notes/MainActivity.kt
> +        val enterpassword = binding.textInputPassword.text
Предыдущий вариарнт был лучше, подумай еще...

2023-02-05 12:37 UTC, LumakanA commented on app/src/main/java/com/example/notes/MainActivity.kt
> +        val enterpassword = binding.textInputPassword.text
что нужно сделать? вынести код в отдельные функции? я не понимаю о какую оптимизацию вы имеете ввиду...

2023-02-06 09:51 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/notes/MainActivity.kt
> +        val enterpassword = binding.textInputPassword.text
В отдельную функцию не нужно выносить.
Может, переменные (email,  enterpassword)  внутри обработчика событий определить, и уже в них передавать результат проверки....

2023-02-06 20:03 UTC, Alexandr-Prokin requested changes

2023-02-06 20:03 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/notes/MainActivity.kt
> +            } else {
Уже лучше! Подумай, как оставить 2 переменные и избавиться от [else]

2023-02-06 20:28 UTC, LumakanA commented on app/src/main/java/com/example/notes/MainActivity.kt
> +            } else {
подсказка будет? :)

2023-02-07 12:40 UTC, merged